### ISSUE TITLE
Tabula exporting function?

### ISSUE THREAD

**Issue by Mremenar** [iChun/Tabula#115]
Dear iChun, First let me say "Thank you!" for Tabula and all the awesome mods that you have contributed to the Minecraft community.  You are a treasure and your generous gifts of time and coding are greatly appreciated!
This is more of a request or inquiry rather than an issue:  Is there any way that Tabula can import a .NBT or .schematic for editing?  My second grader son has built a mob in Minecraft that he would love to edit in Tabula and make an actual entity.  Is there any way to import the model (via MCEdit) into Tabula, or any other-wise?
Thank you in advance,
M

**Comment by iChun** [comment]
Thanks so much for your support! 🙂

Unfortunately, importing a .nbt or .schematic isn't currently possible.
Tabula however, is written in a way that supports importing different
formats in, and people are more than welcome to write their own importers
for other formats.

Due to time constraints, I won't be looking into writing this importer
myself, but if anyone manages to parse the format right, I'd more than
gladly add it to the mod.

**Comment by Mremenar** [comment]
I've never attempted such before.  Is there an easy way to import a build in Minecraft into Tabula?

**Comment by iChun** [comment]
Sorry for the late reply. All importing is done in Java code and requires the user to parse the file and to convert that into a Tabula-understood file. Even Tabula does it for it's own files.
