### ISSUE TITLE
1.15.2 models in 1.12.2

### ISSUE THREAD

**Issue by Darth-Vitiate** [iChun/Tabula#128]
Hello,
 I am aware you most likely need to write a new parsing code but are there any alternatives?

**Comment by iChun** [comment]
I have no plans on back porting the model format, tbh. Only possibility of
using 1.15+ models in 1.12 would be to export as java, back port to 1.12,
have a mod load it up in 1.12 and have tabula import it back in as a new
project.

Tabula's new format was redone since lately Mojang has made a lot of
changes to their Model class and the changes to the format was to closer
match what they were doing, which unfortunately broke model compatibility
with older versions.

Your best bet, if you want to have Tabula models in 1.12.2, would be to
make them on that version. The 1.15.2+ version would be able to load them
up for the most part.

If someone were to PR an importer I wouldn't mind pushing out a new build
of Tabula for 1.12.2 but I personally won't be doing it.
