### ISSUE TITLE
Feature request / Bug report

### ISSUE THREAD

**Issue by heldplayer** [iChun/Tabula#41]
- Multiple texture mappings support to allow multiple models with different textures (example: player model with steve skin and armour model with its own texture)
- Ghost model (whatever that is)
  - &lt;pig&gt; Ghost model Aka a template to make models over
  - &lt;pig&gt; Useful for layer renderer in 1.8
- Collapsing model groups so their contents aren't displayed (useful for large models)
- Make scrolling faster in the tree view, it's horribly slow
- BUG: Moving items in the treeview causes it to scroll to the top

**Comment by iChun** [comment]
more specifically
<pig> heldplayer: I'm out atm. Mind making a new issue on Tabula for a unique texture mappings button, as well as a ghost model button?

**Comment by heldplayer** [comment]
Yeah... that thing

**Comment by iChun** [comment]
Also import a model into a group

**Comment by hunchparty** [comment]
the Minecraft model that I made took a week to make and I still didn't finish it so I took a break for a week and I come back and my model is gone and every time before I leave tabula I save my model and I found out about it today so my suggestion is that you add a folder of some sort to keep models in where the don't get erased so plz add that because I take my models seriously and I'm pissed

**Comment by hunchparty** [comment]
honestly now I don't think I can trust your program until after alought of updates because my models are to precious for me to lose

**Comment by hunchparty** [comment]
nevermind its ok and you don't have to update your saves because its ok and I'm ok now YOU GUYS WORK HARD because your mod is BRILLIANT

**Comment by iChun** [comment]
Lmao thanks I guess??

As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
