### ISSUE TITLE
(1.7.10) Cubes are broken/locked

### ISSUE THREAD

**Issue by Viperfish2000** [iChun/Tabula#92]
I'm trying to make a model, but some of my pieces have locked or something (it doesn't let me edit their size, position, offset, rotation, texture offset, and basically anything else). Originally the error first started occurring when I would copy an object with children, and the children would be broken. Is there a solution to this?

**Comment by Viperfish2000** [comment]
halp

**Comment by iChun** [comment]
... Why are you using the mod on 1.7.10? Try using the 1.8 version. There was a bug with identifiers and children models that was fixed in that version, which is probably the issue you're having. 

Unfortunately I don't think models that were affected by this bug can be salvaged by Tabula unless done so manually.
