### ISSUE TITLE
[Suggestion] Multi-selection

### ISSUE THREAD

**Issue by Spyeedy** [iChun/Tabula#99]
Being allowed to select multiple parts would save the trouble of having to drag the parts individually under a same part as child parts.
Also, multi-selection can enable the user to move multiple parts at a time instead of inputting the new values individually.

**Comment by iChun** [comment]
Ctrl+Click? Or Shift+Click. I can't remember the combo now.

On 9 Apr 2018 10:10 PM, "Spyeedy" <notifications@github.com> wrote:

Being allowed to select multiple parts would save the trouble of having to
drag the parts individually under a same part as child parts.
Also, multi-selection can enable the user to move multiple parts at a time
instead of inputting the new values individually.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/iChun/Tabula/issues/99>, or mute the thread

**Comment by iChun** [comment]
Does it not? Hmm I'll have to look into this again. I remember making this
a feature at some point in time.

**Comment by willsaber** [comment]
I have not used Tabula for quite a minute, but I recall being a little disappointed that this feature never worked for me. The silver lining is that it taught me to use a child-parent work flow, which is ultimately much better than what I was doing with Techne back in the day, but there are still times that I find a multi-select would be useful.

**Comment by iChun** [comment]
As iChunUtil and Tabula has been redone-over (again) for 1.15+. I am closing issues pertaining to 1.12.2 and earlier. 

My apologies that I've not been able to address your issue.
